name: Keep Render Awake v3

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render
        run: |
          curl -L \
            --max-time 30 \
            --retry 3 \
            --retry-delay 5 \
            https://insyt-oukm.onrender.com/ 
